#!/bin/bash
# install.sh
# Installs all of the prerequisites for executing the artefacts generated by Pascani:
# JDK 1.6.0_23, Frascati 1.4 (with enhanced binaries), RabbitMQ, SSH & FTP
# To use execute: sudo -E ./install.sh

function show {
	echo "-----------------------------------"
	echo " $1"
	echo "-----------------------------------"
}

show "ADDING REPOSITORIES"
echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -

show "INSTALLING DEPENDENCIES"
apt-get -y update && apt-get install -y wget unzip vsftpd openssh-server rabbitmq-server

show "ADDING USER frascati:frascati"
useradd -m -s /bin/bash frascati && echo "frascati:frascati" | chpasswd
adduser frascati sudo

show "OPEN SSH & FTP PORTS"
ufw allow ssh
ufw allow ftp

show "CONFIGURING FTP SERVER"
sed -i 's/#write_enable=YES/write_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#local_umask=022/local_umask=022/g' /etc/vsftpd.conf
echo "pasv_enable=Yes" >> /etc/vsftpd.conf
echo "pasv_min_port=40000" >> /etc/vsftpd.conf
echo "pasv_max_port=40100" >> /etc/vsftpd.conf
service vsftpd restart

show "DOWNLOADING FRASCATI"
mkdir /tmp/files
cd /tmp/files
wget -c http://download.forge.ow2.org/frascati/frascati-1.4-bin.zip -P /tmp/files
unzip frascati-1.4-bin.zip -d /opt/
sudo chown -R frascati frascati-runtime-1.4

show "DOWNLOADING JAVA 1.6_23"
wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/6u23-b05/jdk-6u23-linux-x64.bin -P /tmp/files
chmod a+x jdk-6u23-linux-x64.bin
./jdk-6u23-linux-x64.bin
mkdir /opt/jdk
mv jdk1.6.0_23 /opt/jdk
sudo chown -R frascati jdk

show "UPDATING FRASCATI BINARY AND LIBS"
wget https://raw.githubusercontent.com/jachinte/frascati-binaries/master/frascati
mv frascati /opt/frascati-runtime-1.4/bin/
chmod a+x /opt/frascati-runtime-1.4/bin/frascati
wget http://central.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
rm $FRASCATI_HOME/lib/guava-r07.jar
mv guava-18.0.jar $FRASCATI_HOME/lib/guava-18.0.jar

p=0
if [ -z "$JAVA_HOME" ]; then
	p=$((p + 2))
	bash -c 'echo "export JAVA_HOME=/opt/jdk/jdk1.6.0_23" >> /etc/profile'
fi

if [ -z "$FRASCATI_HOME" ]; then
	p=$((p + 3))
	bash -c 'echo "export FRASCATI_HOME=/opt/frascati-runtime-1.4" >> /etc/profile'
fi  

if [ "$p" = 2 ]; then
	bash -c 'echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> /etc/profile'
fi
if [ "$p" = 3 ]; then
	bash -c 'echo "export PATH=\$PATH:\$FRASCATI_HOME/bin" >> /etc/profile'
fi
if [ "$p" = 5 ]; then
	bash -c 'echo "export PATH=\$PATH:\$JAVA_HOME/bin:\$FRASCATI_HOME/bin" >> /etc/profile'
fi

show "CONFIGURING RABBITMQ"
wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/stable/docs/rabbitmq.config.example -P /etc/rabbitmq
mv /etc/rabbitmq/rabbitmq.config.example /etc/rabbitmq/rabbitmq.config
sed -i 's/%% {loopback_users, \[\]},/{loopback_users, \[\]}/g' /etc/rabbitmq/rabbitmq.config
service rabbitmq-server restart

show "INSTALLING RABBITMQ MANAGEMENT PLUGIN"
rabbitmq-plugins enable rabbitmq_management
wget -c http://localhost:15672/cli/rabbitmqadmin -P /opt/rabbitmq-cli
chmod a+x /opt/rabbitmq-cli/rabbitmqadmin

r=false
if ! hash rabbitmqadmin 2>/dev/null; then
	r=true
	p=$((p + 1))
	bash -c 'echo "export PATH=\$PATH:/opt/rabbitmq-cli" >> /etc/profile'
fi

if [ "$p" -gt "0" ]; then
	show "ENVIRONMENT VARIABLES UPDATED"
	. /etc/profile
	show "COPY AND PASTE: source /etc/profile"
fi

if [ "$r" = "true" ]; then
	show "CREATING RABBITMQ EXCHANGES"
	rabbitmqadmin declare exchange --vhost=/ name=namespaces_exchange type=topic -u guest -p guest durable=true
	rabbitmqadmin declare exchange --vhost=/ name=probes_exchange type=direct -u guest -p guest durable=true
	rabbitmqadmin declare exchange --vhost=/ name=monitors_exchange type=direct -u guest -p guest durable=true
	rabbitmqadmin declare exchange --vhost=/ name=logs_namespace type=fanout -u guest -p guest durable=true
	rabbitmqadmin declare exchange --vhost=/ name=rpc_exchange type=direct -u guest -p guest durable=true
fi
